<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8a1cd89bc3e35ce28ac9515007548c67
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LINE\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LINE\\' => 
        array (
            0 => __DIR__ . '/..' . '/linecorp/line-bot-sdk/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8a1cd89bc3e35ce28ac9515007548c67::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8a1cd89bc3e35ce28ac9515007548c67::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8a1cd89bc3e35ce28ac9515007548c67::$classMap;

        }, null, ClassLoader::class);
    }
}
